### ISSUE TITLE
Add an optional meta field

### ISSUE THREAD

**Issue by sngx13** [codeout/inet-henge#30]
Hi,

Is it possible to request a meta field for link state? would be nice to be able to show links in UP/DOWN, i'm pulling data from NMS to generate topology so would be able to push this too and display nicely on the map.

P.S: is there a way of offsetting / aligning interface description to middle of the link?

Thank you.

**Comment by codeout** [comment]
Hi,

inet-henge copies `class` attribute of `node` and `link` to SVG DOM, which means you can change link appearance with CSS.

```json
# .json

"links": [
  { "source": "POP01-bb01", "target": "POP01-bb02",
    "class": "fault",
    "meta": { "foo":  "bar"}
  },
...
```

```css
<style>
    .link.fault {
        stroke-dasharray: 5, 5;
    }
    .link text .foo {
        font-size: 10px;
    }
</style>
```

```js
  diagram.init('loopback', 'interface', 'description', 'type', 'foo');
```

![image](https://user-images.githubusercontent.com/921696/119661276-164f3580-be6b-11eb-9abd-1da2823c834c.png)

P.S. Add `meta` to `link` then call `.init('foo')` to show something at the middle of the link.
