### ISSUE TITLE
Can you show the topology as a tree? 

### ISSUE THREAD

**Issue by chenqun61** [codeout/inet-henge#9]

**Comment by chenqun61** [comment]
hey , friend .
Can you make the topology display in a hierarchical tree structure?
Can you customize the color and thickness of the line?
Thx very much.

**Comment by codeout** [comment]
> Can you make the topology display in a hierarchical tree structure?

No, inet-henge doesn't support that style unfortunately.

> Can you customize the color and thickness of the line?

Yes, css is available. Let's say we have a json below:

```js
{
  "nodes": [
    { "name": "POP1-A" },
    { "name": "POP1-B" },
    { "name": "POP2-A", "icon": "https://inet-henge.herokuapp.com/images/router.png" },
    { "name": "POP2-B", "icon": "https://inet-henge.herokuapp.com/images/router.png" },
    { "name": "POP3-A", "icon": "https://inet-henge.herokuapp.com/images/router.png" }
  ],

  "links": [
    { "source": "POP1-A", "target": "POP1-B",
      "meta": { "interface": { "source": "ge-0/{0,1}/0", "target": "Te0/{0,1}/0/0" }, "bandwidth": "20G" } },
    { "source": "POP2-A", "target": "POP2-B",
      "meta": { "interface": { "source": "ge-0/{0,1}/0", "target": "Te0/0/{0,1}/0" }, "bandwidth": "20G" } },
    { "source": "POP1-A", "target": "POP2-A",
      "meta": { "interface": { "source": "ge-0/0/1", "target": "Te0/0/0/1" }, "bandwidth": "10G" } },
    { "source": "POP1-B", "target": "POP2-B",
      "meta": { "interface": { "source": "ge-0/0/1", "target": "Te0/0/0/1" }, "bandwidth": "10G" } },
    { "source": "POP3-A", "target": "POP2-B"}
  ]
}
```

And apply this:

```css
.group rect { opacity: 0.5; }
.node, .group rect { cursor: move; }

.group.pop1 rect { fill: #4ecdc4 !important; }
.node.pop1-a rect { fill: #c7f464 !important; }
.link.pop1-a-pop1-b { stroke: #c44d58; }

.link:hover { stroke-width: 5px; }
.link:hover ~ .path-label {
   font-weight: bold;
   visibility: visible !important;
}
```

<-- default style / customized style -->
![image](https://user-images.githubusercontent.com/921696/41909151-44980c3c-7981-11e8-8caa-8982fb29c0de.png)
